// GENERATED — do not edit by hand.
//
// Rebuild with:
//   node scripts/build-qualifications.mjs <journal.jsonl>
//
// Source: a six-way research fan-out over S-BB, BIG-register, CZO, V&VN and DUO,
// each segment then checked by an adversarial verifier whose job was to find
// invented CREBO codes, wrong BIG status and outdated names. 65 corrections and
// 22 missing qualifications came out of that pass and are applied here.
//
// CREBO codes are present only where a verifier could confirm them. A missing code
// is deliberate: a facility may check it, and a wrong code is worse than none.

import type { Qualification } from "@/lib/qualifications";

export const QUALIFICATION_DATA: Qualification[] = [
  {
    slug: "verzorgende-ig-niveau-3",
    nameNl: "Verzorgende IG",
    shortNl: "Verzorgende IG (VIG'er)",
    aliases: ["Verzorgende-IG","VIG","VIG'er","Verzorgende Individuele Gezondheidszorg","Verzorgende individuele gezondheidszorg","Verzorgende niveau 3","VIG niveau 3","Verzorgende IG'er","Ziekenverzorgende (oud)","Verpleeghuisverzorgende"],
    category: "mbo_verpleging_verzorging",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    bigStatus: "big_artikel_34",
    settings: ["VVT (verpleeghuis, verzorgingshuis)","thuiszorg / wijkverpleging","gehandicaptenzorg","GGZ","kraamzorg","ziekenhuis (beperkt)"],
  },
  {
    slug: "mbo-verpleegkundige-niveau-4",
    nameNl: "Mbo-Verpleegkundige",
    shortNl: "Verpleegkundige niveau 4 (mbo-V)",
    aliases: ["mbo-verpleegkundige","hbo-verpleegkundige","verpleegkundige niveau 4","verpleegkundige niveau 5","VP","HBO-V","BIG-geregistreerd verpleegkundige","MBO-Verpleegkundige","mbo-V","MBO-V","Verpleegkundige niveau 4","VP niveau 4","Verpleegkundige (BIG)","Mbo-Verpleegkundige ziekenhuis (ZH)","Mbo-Verpleegkundige VVT","Mbo-Verpleegkundige GGZ","Mbo-Verpleegkundige GHZ","A-verpleegkundige (inservice, oud)","B-verpleegkundige (inservice, oud)","Z-verpleegkundige (inservice, oud)","Verpleegkundige","move inservice diplomas to their own 'overig' row."],
    category: "mbo_verpleging_verzorging",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "27145",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","GGZ","gehandicaptenzorg","thuiszorg","wijkverpleging","VVT (verpleeghuis, verzorgingshuis)","thuiszorg / wijkverpleging","revalidatie","hospice"],
  },
  {
    slug: "assistent-dienstverlening-entree-niveau-1",
    nameNl: "Assistent dienstverlening",
    shortNl: "Assistent dienstverlening (entree, niveau 1)",
    aliases: ["Assistent dienstverlening en zorg","Assistent Dienstverlening en Zorg (ADZ)","ADZ","Entree Zorg & Welzijn","Entreeopleiding zorg","Entree niveau 1","Assistent zorg en welzijn","Zorghulp (entree)"],
    category: "mbo_verpleging_verzorging",
    levelLabel: "MBO niveau 1 (entreeopleiding)",
    mboLevel: 1,
    crebo: "25741",
    bigStatus: "geen_big",
    settings: ["VVT (verpleeg- en verzorgingshuizen)","thuiszorg","gehandicaptenzorg","ziekenhuis (ondersteunend/facilitair)","kinderopvang"],
  },
  {
    slug: "verzorgende-oud-diploma-voor-ig",
    nameNl: "Verzorgende (oud diploma, vóór invoering Verzorgende IG)",
    shortNl: "Verzorgende (oud diploma)",
    aliases: ["Verzorgende","Verzorgende niveau 3 (oud)","Ziekenverzorgende","MDGO-VP","MDGO-VZ","Bejaardenverzorgende","Gezinsverzorgende","Verzorgende in verzorgingshuizen","Verzorgende C"],
    category: "mbo_verpleging_verzorging",
    levelLabel: "MBO niveau 3 (historische diploma's)",
    mboLevel: 3,
    bigStatus: "onbekend",
    settings: ["VVT","thuiszorg","gehandicaptenzorg"],
  },
  {
    slug: "verzorgende-ig",
    nameNl: "Verzorgende in de individuele gezondheidszorg",
    shortNl: "Verzorgende IG",
    aliases: ["VIG","VIG'er","verzorgende-IG","verzorgende niveau 3","VIG niveau 3","verzorgende IG (VIG)"],
    category: "mbo_verpleging_verzorging",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    bigStatus: "big_artikel_34",
    settings: ["VVT","verpleeghuis","thuiszorg","gehandicaptenzorg","GGZ"],
  },
  {
    slug: "zorghulp",
    nameNl: "Zorghulp",
    shortNl: "Zorghulp",
    aliases: ["Zorghulp niveau 1","Zorgassistent","Zorgondersteuner","Hulp bij de zorg"],
    category: "mbo_verpleging_verzorging",
    levelLabel: "Geen actuele mbo-kwalificatie (historisch niveau 1/2; nu vooral functietitel)",
    bigStatus: "geen_big",
    settings: ["VVT","thuiszorg","gehandicaptenzorg","dagbesteding"],
  },
  {
    slug: "begeleider-gehandicaptenzorg-niveau-3",
    nameNl: "Begeleider gehandicaptenzorg",
    shortNl: "Begeleider gehandicaptenzorg (niveau 3)",
    aliases: ["BGZ","Begeleider GHZ","Begeleider gehandicaptenzorg niveau 3","MMZ Begeleider gehandicaptenzorg","MZ BGZ"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    crebo: "25475",
    bigStatus: "geen_big",
    settings: ["gehandicaptenzorg","woonvoorziening VG/LVB","dagbesteding","logeerhuis","ambulante begeleiding"],
  },
  {
    slug: "persoonlijk-begeleider-gehandicaptenzorg-niveau-4",
    nameNl: "Persoonlijk begeleider gehandicaptenzorg",
    shortNl: "PB gehandicaptenzorg (niveau 4)",
    aliases: ["PBGZ","PB GHZ","PB'er gehandicaptenzorg","Persoonlijk begeleider GHZ","MMZ PBGZ"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25477",
    bigStatus: "geen_big",
    settings: ["gehandicaptenzorg","woonvoorziening VG/LVB/EMB","dagbesteding","ambulante begeleiding","gezinshuis"],
  },
  {
    slug: "persoonlijk-begeleider-specifieke-doelgroepen-niveau-4",
    nameNl: "Persoonlijk begeleider specifieke doelgroepen",
    shortNl: "PB specifieke doelgroepen (niveau 4)",
    aliases: ["PBSD","PB SD","PB'er specifieke doelgroepen","MMZ PBSD"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25478",
    bigStatus: "geen_big",
    settings: ["GGZ","beschermd wonen","maatschappelijke opvang","verslavingszorg","forensische zorg","jeugdzorg","asielopvang"],
  },
  {
    slug: "begeleider-maatschappelijke-zorg-niveau-3",
    nameNl: "Begeleider maatschappelijke zorg",
    shortNl: "Begeleider MZ (niveau 3)",
    aliases: ["BMZ","Begeleider MZ","Begeleider maatschappelijke zorg niveau 3","MZ niveau 3","Begeleider niveau 3"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    crebo: "25780",
    bigStatus: "geen_big",
    settings: ["gehandicaptenzorg","GGZ","VVT","thuiszorg","maatschappelijke opvang","beschermd wonen","asielopvang (COA)","justitiele inrichtingen","dagbesteding"],
  },
  {
    slug: "agogisch-medewerker-ggz-niveau-4",
    nameNl: "Agogisch medewerker GGZ",
    shortNl: "Agogisch medewerker GGZ (niveau 4)",
    aliases: ["AMG","Agogisch medewerker geestelijke gezondheidszorg","Sociaal psychiatrisch begeleider (functienaam)","Begeleider GGZ niveau 4"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25474",
    bigStatus: "geen_big",
    settings: ["GGZ","klinische GGZ-afdeling","beschermd wonen","FACT-team","verslavingszorg","forensische psychiatrie"],
  },
  {
    slug: "begeleider-specifieke-doelgroepen-niveau-3",
    nameNl: "Begeleider specifieke doelgroepen",
    shortNl: "Begeleider specifieke doelgroepen (niveau 3)",
    aliases: ["BSD","Begeleider SD","MMZ Begeleider specifieke doelgroepen"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    crebo: "25476",
    bigStatus: "geen_big",
    settings: ["GGZ","maatschappelijke opvang","beschermd wonen","verslavingszorg","dak- en thuislozenopvang","asielopvang","VVT (psychogeriatrie)","justitiele inrichtingen"],
  },
  {
    slug: "gespecialiseerd-pedagogisch-medewerker-niveau-4",
    nameNl: "Gespecialiseerd pedagogisch medewerker",
    shortNl: "GPM (niveau 4)",
    aliases: ["GPM","Gespecialiseerd pedagogisch medewerker kinderopvang","PW4","Pedagogisch werk niveau 4","Gespecialiseerd pedagogisch medewerker 4","Add \"SPW 4\"","\"SPW niveau 4\"","\"Sociaal pedagogisch werker 4\""],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25697",
    bigStatus: "geen_big",
    settings: ["kinderopvang","IKC","VVE/peuteropvang","medisch kinderdagverblijf","kinderdagcentrum gehandicaptenzorg","jeugdzorg","gezinshuis"],
  },
  {
    slug: "medewerker-maatschappelijke-zorg-mmz",
    nameNl: "Medewerker maatschappelijke zorg (MMZ)",
    shortNl: "MMZ",
    aliases: ["MMZ","Medewerker Maatschappelijke Zorg","MZ","Maatschappelijke zorg","MMZ niveau 3","MMZ niveau 4"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3 of 4 (verzamelnaam)",
    bigStatus: "geen_big",
    settings: ["gehandicaptenzorg","GGZ","VVT","maatschappelijke opvang","dagbesteding"],
  },
  {
    slug: "onderwijsassistent-niveau-4",
    nameNl: "Onderwijsassistent",
    shortNl: "Onderwijsassistent (niveau 4)",
    aliases: ["OA","Onderwijsassistent niveau 4","Klassenassistent","Onderwijsondersteuner (functienaam)"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25698",
    bigStatus: "geen_big",
    settings: ["speciaal onderwijs (SO/VSO)","cluster 3 onderwijs","regulier primair onderwijs","IKC","kinderdagcentrum","onderwijs-zorgarrangementen"],
  },
  {
    slug: "persoonlijk-begeleider-maatschappelijke-zorg-niveau-4",
    nameNl: "Persoonlijk begeleider maatschappelijke zorg",
    shortNl: "PB maatschappelijke zorg (niveau 4)",
    aliases: ["PBMZ","PB MZ","PB'er maatschappelijke zorg","Persoonlijk begeleider MZ","MZ niveau 4","Persoonlijk begeleider niveau 4"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25779",
    bigStatus: "geen_big",
    settings: ["gehandicaptenzorg","GGZ","VVT","thuiszorg","beschermd wonen","maatschappelijke opvang","dagbesteding","forensische zorg"],
  },
  {
    slug: "persoonlijk-begeleider-zorgboerderij-niveau-4",
    nameNl: "Persoonlijk werkbegeleider zorgboerderij (old name 'Persoonlijk begeleider zorgboerderij' moves to aliases)",
    shortNl: "PB zorgboerderij (niveau 4)",
    aliases: ["PB zorgboerderij","Begeleider zorgboerderij","Zorgboer begeleider","Groene zorg begeleider"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    bigStatus: "geen_big",
    settings: ["zorgboerderij","dagbesteding","groene zorg","gehandicaptenzorg dagbesteding","GGZ dagbesteding","arbeidsmatige dagbesteding"],
  },
  {
    slug: "pedagogisch-medewerker-kinderopvang-niveau-3",
    nameNl: "Pedagogisch medewerker kinderopvang",
    shortNl: "PMK / pedagogisch medewerker (niveau 3)",
    aliases: ["PMK","PW3","Pedagogisch medewerker","Pedagogisch werk niveau 3","Pedagogisch medewerker kinderopvang niveau 3"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    crebo: "25696",
    bigStatus: "geen_big",
    settings: ["kinderopvang","BSO","peuteropvang/VVE","IKC","kinderdagcentrum gehandicaptenzorg","logeeropvang"],
  },
  {
    slug: "sociaal-werker-niveau-4",
    nameNl: "Sociaal werker",
    shortNl: "Sociaal werker (niveau 4)",
    aliases: ["SW","Sociaal werk","Sociaal werker niveau 4","MBO sociaal werker","Sociaal Werker MBO"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25958",
    bigStatus: "geen_big",
    settings: ["welzijnswerk","sociaal wijkteam","Wmo-begeleiding","maatschappelijke opvang","GGZ ambulant","jeugd- en jongerenwerk","buurtwerk"],
  },
  {
    slug: "sociaal-cultureel-werker-niveau-4",
    nameNl: "Sociaal-cultureel werker",
    shortNl: "Sociaal-cultureel werker (niveau 4)",
    aliases: ["SCW","Sociaal cultureel werker","Welzijnswerker"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25488",
    bigStatus: "geen_big",
    settings: ["welzijnswerk","buurthuis","jongerenwerk","dagbesteding","activiteitenbegeleiding","ouderenwerk"],
  },
  {
    slug: "sociaal-maatschappelijk-dienstverlener-niveau-4",
    nameNl: "Sociaal-maatschappelijk dienstverlener",
    shortNl: "Sociaal-maatschappelijk dienstverlener (niveau 4)",
    aliases: ["SMD","Sociaal maatschappelijk dienstverlener","Maatschappelijk dienstverlener"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25489",
    bigStatus: "geen_big",
    settings: ["sociaal wijkteam","maatschappelijke dienstverlening","schuldhulpverlening","clientondersteuning","maatschappelijke opvang"],
  },
  {
    slug: "sociaal-pedagogisch-werker-legacy",
    nameNl: "Sociaal Pedagogisch Werker (SPW, oud diploma)",
    shortNl: "SPW (oud diploma)",
    aliases: ["SPW 3","SPW 4","sociaal pedagogisch werk"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3/4 (historisch)",
    bigStatus: "geen_big",
    settings: ["gehandicaptenzorg","jeugdzorg","GGZ"],
  },
  {
    slug: "thuisbegeleider-niveau-4",
    nameNl: "Thuisbegeleider",
    shortNl: "Thuisbegeleider (niveau 4)",
    aliases: ["TB","Thuisbegeleiding","Ambulant thuisbegeleider"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "25479",
    bigStatus: "geen_big",
    settings: ["thuisbegeleiding","ambulante begeleiding","Wmo-begeleiding","gezinsbegeleiding","GGZ ambulant"],
  },
  {
    slug: "werkbegeleider-zorgboerderij",
    nameNl: "Werkbegeleider zorgboerderij",
    shortNl: "Werkbegeleider zorgboerderij",
    aliases: ["zorgboerderij","groene zorg"],
    category: "mbo_welzijn_begeleiding",
    levelLabel: "MBO niveau 3",
    bigStatus: "geen_big",
    settings: ["zorgboerderij","dagbesteding"],
  },
  {
    slug: "helpende-zorg-en-welzijn-niveau-2",
    nameNl: "Helpende Zorg en Welzijn",
    shortNl: "Helpende Zorg en Welzijn (niveau 2)",
    aliases: ["HZW","Helpende","Helpende zorg & welzijn","Helpende niveau 2","Helpende Plus (met keuzedeel K1296)","Helpende Zorg & Welzijn","Helpende ZW","Dienstverlener Helpende Zorg & Welzijn","Zorghulp","Zorgassistent","helpende","helpende plus","helpende niveau 2","helpende zorg & welzijn"],
    category: "mbo_assisterend",
    levelLabel: "MBO niveau 2",
    mboLevel: 2,
    crebo: "25960",
    bigStatus: "geen_big",
    settings: ["VVT","thuiszorg","gehandicaptenzorg","dagbesteding","huishoudelijke ondersteuning Wmo","woonzorgcentrum","VVT (verpleeghuis, verzorgingshuis)","GGZ (beschermd wonen)","ziekenhuis","kinderopvang","welzijn"],
  },
  {
    slug: "doktersassistent",
    nameNl: "Doktersassistent",
    shortNl: "Doktersassistent",
    aliases: ["DA","Doktersassistente","Doktersassistent niveau 4","crebo 25695","crebo 25473","Assisterende gezondheidszorg - Doktersassistent","doktersassistente","assistent huisartsenpraktijk","triagist (functie)"],
    category: "mbo_assisterend",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "27142",
    bigStatus: "geen_big",
    settings: ["huisartsenpraktijk","huisartsenpost","ziekenhuis (polikliniek)","GGD","bedrijfsgezondheidszorg","ZBC","ziekenhuis (poli)"],
  },
  {
    slug: "apothekersassistent",
    nameNl: "Apothekersassistent",
    shortNl: "Apothekersassistent",
    aliases: ["AA","Apothekersassistente","Apothekersassistent niveau 4","crebo 25650","apotheekassistent","apothekersassistente"],
    category: "mbo_assisterend",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "27141",
    bigStatus: "big_artikel_34",
    settings: ["openbare apotheek","ziekenhuisapotheek","poliklinische apotheek","apotheekhoudende huisartsenpraktijk","farmaceutische groothandel"],
  },
  {
    slug: "medewerker-steriele-medische-hulpmiddelen",
    nameNl: "Medewerker Steriele Medische Hulpmiddelen",
    shortNl: "MSMH",
    aliases: ["MSMH","Medewerker SMH","CSA-medewerker","Sterilisatiemedewerker","Medewerker Centrale Sterilisatie Afdeling"],
    category: "mbo_assisterend",
    levelLabel: "MBO niveau 3",
    mboLevel: 3,
    crebo: "27030",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (CSA)","ZBC","sterilisatiebedrijf","tandartspraktijk (grote praktijken)"],
  },
  {
    slug: "tandartsassistent",
    nameNl: "Tandartsassistent",
    shortNl: "Tandartsassistent",
    aliases: ["TA","Tandartsassistente","Tandartsassistent niveau 4","crebo 25699","Mondzorgassistent"],
    category: "mbo_assisterend",
    levelLabel: "MBO niveau 4",
    mboLevel: 4,
    crebo: "27143",
    bigStatus: "geen_big",
    settings: ["tandartspraktijk","orthodontiepraktijk","kaakchirurgie","mondzorgcentrum","ZBC"],
  },
  {
    slug: "hbo-verpleegkunde-bachelor",
    nameNl: "Verpleegkunde (hbo-bachelor)",
    shortNl: "HBO-V",
    aliases: ["HBO-V","HBO-Verpleegkunde","Bachelor Nursing","Bachelor of Nursing","BN2020","Opleiding tot Verpleegkundige","hbo-verpleegkundige","verpleegkundige niveau 6","BSc Verpleegkunde"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34560",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","GGZ","gehandicaptenzorg","thuiszorg","revalidatie","wijkverpleging"],
  },
  {
    slug: "bachelor-medisch-hulpverlener",
    nameNl: "Bachelor medisch hulpverlener",
    shortNl: "BMH",
    aliases: ["BMH","medisch hulpverlener","medisch hulpverlener acute zorg (MHAZ)"],
    category: "hbo",
    levelLabel: "HBO bachelor (Medische Hulpverlening)",
    bigStatus: "geen_big",
    settings: ["SEH","ambulancezorg","OK/anesthesie","cardiodiagnostiek"],
  },
  {
    slug: "hbo-medische-hulpverlening-bachelor",
    nameNl: "Medische Hulpverlening (hbo-bachelor)",
    shortNl: "BMH / bachelor medisch hulpverlener",
    aliases: ["BMH","Bachelor Medische Hulpverlening","bachelor medisch hulpverlener","medisch hulpverlener acute zorg","MHAZ","BMH-er"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "30023",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (SEH)","ambulancezorg","OK / anesthesie","acute zorg"],
  },
  {
    slug: "medisch-hulpverlener-acute-zorg",
    nameNl: "Medisch Hulpverlener Acute Zorg",
    shortNl: "BMH / MHAZ",
    aliases: ["BMH","Bachelor Medisch Hulpverlener","MHAZ","Medisch hulpverlener","Bachelor Medisch Hulpverlener Acute Zorg"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (SEH)","ambulancedienst","OK/anesthesie","cardiodiagnostiek/interventiecardiologie","ZBC"],
  },
  {
    slug: "hbo-voeding-en-dietetiek-bachelor",
    nameNl: "Voeding en Diëtetiek (hbo-bachelor)",
    shortNl: "Diëtist",
    aliases: ["Voeding en Dietetiek","Diëtetiek","Nutrition and Dietetics","dietist","diëtiste"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34579",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis","VVT","eerstelijnspraktijk","thuiszorg","GGZ"],
  },
  {
    slug: "dietist",
    nameNl: "Diëtist",
    shortNl: "Diëtist",
    aliases: ["dietist","dietiste"],
    category: "hbo",
    levelLabel: "HBO bachelor (Voeding en Diëtetiek)",
    bigStatus: "big_artikel_34",
    settings: ["eerstelijnspraktijk","ziekenhuis","VVT","thuiszorg"],
  },
  {
    slug: "hbo-ergotherapie-bachelor",
    nameNl: "Ergotherapie (hbo-bachelor)",
    shortNl: "Ergotherapeut",
    aliases: ["Ergotherapie","Opleiding voor Ergotherapie","Occupational Therapy","ergo"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34574",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis","VVT","revalidatie","thuiszorg","gehandicaptenzorg","eerstelijnspraktijk"],
  },
  {
    slug: "ergotherapeut",
    nameNl: "Ergotherapeut",
    shortNl: "Ergotherapeut",
    aliases: ["ergo"],
    category: "hbo",
    levelLabel: "HBO bachelor (Ergotherapie)",
    bigStatus: "big_artikel_34",
    settings: ["revalidatie","VVT","ziekenhuis","eerstelijnspraktijk","gehandicaptenzorg"],
  },
  {
    slug: "hbo-fysiotherapie-bachelor",
    nameNl: "Fysiotherapie (hbo-bachelor)",
    shortNl: "Fysiotherapeut",
    aliases: ["Fysiotherapie","Opleiding tot Fysiotherapeut","Physiotherapy","fysio","BSc Fysiotherapie"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34570",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","revalidatie","eerstelijnspraktijk","gehandicaptenzorg","geriatrische revalidatiezorg"],
  },
  {
    slug: "fysiotherapeut",
    nameNl: "Fysiotherapeut",
    shortNl: "Fysiotherapeut",
    aliases: ["fysio","FT"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    bigStatus: "big_artikel_3",
    settings: ["eerstelijnspraktijk","ziekenhuis","VVT","revalidatie","gehandicaptenzorg"],
  },
  {
    slug: "hartfunctielaborant",
    nameNl: "Hartfunctielaborant",
    shortNl: "Hartfunctielaborant",
    aliases: ["Cardiodiagnostisch medewerker","Medewerker hartfunctie","HCK-medewerker","Medewerker interventiecardiologie","Echocardiografist"],
    category: "hbo",
    levelLabel: "HBO bachelor (duaal)",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (hartfunctieafdeling)","hartcatheterisatiekamer","cardiologie poli","ZBC"],
  },
  {
    slug: "hbo-huidtherapie-bachelor",
    nameNl: "Huidtherapie (hbo-bachelor)",
    shortNl: "Huidtherapeut",
    aliases: ["Huidtherapie","huidtherapeute","Skin Therapy"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34091",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (dermatologie)","huidtherapiepraktijk","wondzorg","brandwondencentrum","oedeemzorg"],
  },
  {
    slug: "huidtherapeut",
    nameNl: "Huidtherapeut",
    shortNl: "Huidtherapeut",
    aliases: ["huidtherapie"],
    category: "hbo",
    levelLabel: "HBO bachelor (Huidtherapie)",
    bigStatus: "big_artikel_34",
    settings: ["huidtherapiepraktijk","ziekenhuis (dermatologie)"],
  },
  {
    slug: "hbo-logopedie-bachelor",
    nameNl: "Logopedie (hbo-bachelor)",
    shortNl: "Logopedist",
    aliases: ["Logopedie","Opleiding voor Logopedie","Speech and Language Therapy","logopedist"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34578",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis","VVT","revalidatie","onderwijs/speciaal onderwijs","eerstelijnspraktijk","gehandicaptenzorg"],
  },
  {
    slug: "logopedist",
    nameNl: "Logopedist",
    shortNl: "Logopedist",
    aliases: ["logopedie","spraaktherapeut"],
    category: "hbo",
    levelLabel: "HBO bachelor (Logopedie)",
    bigStatus: "big_artikel_34",
    settings: ["eerstelijnspraktijk","ziekenhuis","VVT","revalidatie","onderwijs/zorg"],
  },
  {
    slug: "hbo-master-advanced-nursing-practice",
    nameNl: "Master Advanced Nursing Practice (MANP)",
    shortNl: "MANP",
    aliases: ["MANP","Master ANP","Advanced Nursing Practice","opleiding tot verpleegkundig specialist","M ANP"],
    category: "hbo",
    levelLabel: "HBO master",
    crebo: "49246",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","VVT","GGZ","huisartsenzorg","gehandicaptenzorg"],
  },
  {
    slug: "radiodiagnostisch-laborant",
    nameNl: "Radiodiagnostisch laborant",
    shortNl: "MBB'er (radiodiagnostiek)",
    aliases: ["MBB'er","medisch beeldvormings- en bestralingsdeskundige","MBB-er radiologie","laborant radiologie","MBRT"],
    category: "hbo",
    levelLabel: "HBO bachelor (Medische Beeldvorming en Radiotherapeutische Technieken)",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (radiologie)","nucleaire geneeskunde","zelfstandig behandelcentrum"],
  },
  {
    slug: "radiotherapeutisch-laborant",
    nameNl: "Radiotherapeutisch laborant",
    shortNl: "MBB'er (radiotherapie)",
    aliases: ["MBB'er radiotherapie","medisch beeldvormings- en bestralingsdeskundige","bestralingslaborant","MBRT"],
    category: "hbo",
    levelLabel: "HBO bachelor (Medische Beeldvorming en Radiotherapeutische Technieken)",
    bigStatus: "big_artikel_34",
    settings: ["radiotherapeutisch centrum","ziekenhuis"],
  },
  {
    slug: "hbo-mbrt-bachelor",
    nameNl: "Medisch Beeldvormende en Radiotherapeutische Technieken (hbo-bachelor)",
    shortNl: "MBRT / MBB'er",
    aliases: ["MBRT","MBB'er","medisch beeldvormings- en bestralingsdeskundige","radiodiagnostisch laborant","radiotherapeutisch laborant","laborant radiologie","Medical Imaging and Radiation Therapy"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34561",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (radiologie)","radiotherapie-instituut","nucleaire geneeskunde","zelfstandig behandelcentrum"],
  },
  {
    slug: "hbo-mondzorgkunde-bachelor",
    nameNl: "Mondzorgkunde (hbo-bachelor)",
    shortNl: "Mondhygiënist",
    aliases: ["Mondzorgkunde","mondhygienist","mondhygiëniste","Oral Hygiene","Dental Hygiene"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34576",
    bigStatus: "big_artikel_34",
    settings: ["tandartspraktijk","mondzorgpraktijk","ziekenhuis","GGD","VVT (mondzorg bij ouderen)"],
  },
  {
    slug: "mondhygienist",
    nameNl: "Mondhygiënist",
    shortNl: "Mondhygiënist",
    aliases: ["mondhygienist","MH"],
    category: "hbo",
    levelLabel: "HBO bachelor (Mondzorgkunde)",
    bigStatus: "big_artikel_34",
    settings: ["tandartspraktijk","mondzorgpraktijk","VVT (mondzorg)"],
  },
  {
    slug: "hbo-oefentherapie-bachelor",
    nameNl: "Oefentherapie (Cesar / Mensendieck) (hbo-bachelor)",
    shortNl: "Oefentherapeut",
    aliases: ["Oefentherapie","Oefentherapie Cesar","Oefentherapie Mensendieck","Opleiding tot Oefentherapeut-Mensendieck","oefentherapeut Cesar","oefentherapeut Mensendieck"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    bigStatus: "big_artikel_34",
    settings: ["eerstelijnspraktijk","revalidatie","VVT","bedrijfsgezondheidszorg"],
  },
  {
    slug: "oefentherapeut",
    nameNl: "Oefentherapeut",
    shortNl: "Oefentherapeut",
    aliases: ["oefentherapeut Cesar","oefentherapeut Mensendieck","oefentherapie Cesar/Mensendieck"],
    category: "hbo",
    levelLabel: "HBO bachelor (Oefentherapie Cesar of Mensendieck)",
    bigStatus: "big_artikel_34",
    settings: ["eerstelijnspraktijk","revalidatie","VVT"],
  },
  {
    slug: "hbo-optometrie-bachelor",
    nameNl: "Optometrie (hbo-bachelor)",
    shortNl: "Optometrist",
    aliases: ["Optometrie","optometrist","Optometry"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34549",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (oogheelkunde)","zelfstandig behandelcentrum","optiekzaak","oogkliniek"],
  },
  {
    slug: "optometrist",
    nameNl: "Optometrist",
    shortNl: "Optometrist",
    aliases: ["optometrie"],
    category: "hbo",
    levelLabel: "HBO bachelor (Optometrie)",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (oogheelkunde)","optiek/optometriepraktijk"],
  },
  {
    slug: "hbo-orthoptie-bachelor",
    nameNl: "Orthoptie (hbo-bachelor)",
    shortNl: "Orthoptist",
    aliases: ["Orthoptie","orthoptist","orthoptiste","Orthoptics"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34577",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (oogheelkunde)","oogkliniek","zelfstandig behandelcentrum","jeugdgezondheidszorg"],
  },
  {
    slug: "orthoptist",
    nameNl: "Orthoptist",
    shortNl: "Orthoptist",
    aliases: ["orthoptie"],
    category: "hbo",
    levelLabel: "HBO bachelor (Orthoptie)",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis (oogheelkunde)","orthoptiepraktijk"],
  },
  {
    slug: "physician-assistant",
    nameNl: "Physician assistant",
    shortNl: "PA",
    aliases: ["physician assistant (PA)","MPA","Master Physician Assistant"],
    category: "hbo",
    levelLabel: "HBO master (Master Physician Assistant)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","huisartsenzorg","VVT","GGZ","SEH"],
  },
  {
    slug: "hbo-pedagogiek-bachelor",
    nameNl: "Pedagogiek (hbo-bachelor)",
    shortNl: "Pedagoog (hbo)",
    aliases: ["Pedagogiek","hbo-pedagoog","Bachelor Pedagogiek","opvoedkundige"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "35158",
    bigStatus: "geen_big",
    settings: ["jeugdzorg","gehandicaptenzorg","onderwijs","kinderopvang","GGZ (jeugd)","wijkteam"],
  },
  {
    slug: "hbo-master-physician-assistant",
    nameNl: "Master Physician Assistant (MPA)",
    shortNl: "Physician Assistant (PA)",
    aliases: ["PA","MPA","Physician Assistant","Master Physician Assistant","physician assistant klinisch verloskundige"],
    category: "hbo",
    levelLabel: "HBO master",
    crebo: "49115",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","huisartsenzorg","VVT","GGZ","zelfstandig behandelcentrum"],
  },
  {
    slug: "hbo-podotherapie-bachelor",
    nameNl: "Podotherapie (hbo-bachelor)",
    shortNl: "Podotherapeut",
    aliases: ["Opleiding Podotherapie","Podotherapie","podotherapeut","voetzorg"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34581",
    bigStatus: "big_artikel_34",
    settings: ["podotherapiepraktijk","ziekenhuis (diabetische voet)","VVT","eerstelijnszorg"],
  },
  {
    slug: "podotherapeut",
    nameNl: "Podotherapeut",
    shortNl: "Podotherapeut",
    aliases: ["podotherapie"],
    category: "hbo",
    levelLabel: "HBO bachelor (Podotherapie)",
    bigStatus: "big_artikel_34",
    settings: ["podotherapiepraktijk","diabeteszorg","VVT"],
  },
  {
    slug: "hbo-social-work-bachelor",
    nameNl: "Social Work (hbo-bachelor)",
    shortNl: "Social worker",
    aliases: ["Social Work","SW","Maatschappelijk Werk en Dienstverlening","MWD","Sociaal Pedagogische Hulpverlening","SPH","Culturele en Maatschappelijke Vorming","CMV","sociaal werker","Bachelor of Social Work"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34116",
    bigStatus: "geen_big",
    settings: ["GGZ","gehandicaptenzorg","jeugdzorg","maatschappelijke opvang","wijkteam","forensische zorg","VVT"],
  },
  {
    slug: "tandprotheticus",
    nameNl: "Tandprotheticus",
    shortNl: "Tandprotheticus",
    aliases: ["tandprothetiek","kunstgebitspecialist"],
    category: "hbo",
    levelLabel: "HBO opleiding Tandprothetiek (niveauaanduiding niet apart geverifieerd)",
    bigStatus: "big_artikel_34",
    settings: ["tandprothetische praktijk","tandartspraktijk"],
  },
  {
    slug: "hbo-toegepaste-gerontologie-bachelor",
    nameNl: "Toegepaste Gerontologie (hbo-bachelor)",
    shortNl: "Toegepast gerontoloog",
    aliases: ["Toegepaste Gerontologie","gerontoloog","Age friendly design & innovation","Applied Gerontology"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    bigStatus: "geen_big",
    settings: ["VVT","ouderenzorg","gemeente / beleid","welzijnsorganisatie","zorgtechnologie"],
  },
  {
    slug: "hbo-toegepaste-psychologie-bachelor",
    nameNl: "Toegepaste Psychologie (hbo-bachelor)",
    shortNl: "Toegepast psycholoog (TP)",
    aliases: ["Toegepaste Psychologie","TP","hbo-psycholoog","Applied Psychology"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34507",
    bigStatus: "geen_big",
    settings: ["GGZ","jeugdzorg","re-integratie","arbeid & organisatie","gehandicaptenzorg"],
  },
  {
    slug: "vaktherapeut",
    nameNl: "Vaktherapeut",
    shortNl: "Vaktherapeut",
    aliases: ["vaktherapie","creatief therapeut","beeldend therapeut","muziektherapeut","psychomotorisch therapeut"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    bigStatus: "geen_big",
    settings: ["GGZ","gehandicaptenzorg","jeugdzorg"],
  },
  {
    slug: "hbo-verloskunde-bachelor",
    nameNl: "Verloskunde (hbo-bachelor)",
    shortNl: "Verloskundige",
    aliases: ["Verloskunde","Midwifery","Opleiding tot Verloskundige","eerstelijns verloskundige","klinisch verloskundige"],
    category: "hbo",
    levelLabel: "HBO bachelor",
    crebo: "34134",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","verloskundigenpraktijk","geboortecentrum","kraamzorg"],
  },
  {
    slug: "verloskundige",
    nameNl: "Verloskundige",
    shortNl: "Verloskundige",
    aliases: ["vroedvrouw","midwife","waarnemend verloskundige"],
    category: "hbo",
    levelLabel: "HBO bachelor (Verloskunde)",
    bigStatus: "big_artikel_3",
    settings: ["verloskundigenpraktijk","ziekenhuis (klinisch verloskundige)","geboortecentrum"],
  },
  {
    slug: "wo-farmacie-apotheker",
    nameNl: "Farmacie (wo) - apotheker",
    shortNl: "Apotheker",
    aliases: ["Farmacie","apotheker","openbaar apotheker","ziekenhuisapotheker","Pharmacy"],
    category: "wo",
    levelLabel: "WO master",
    bigStatus: "big_artikel_3",
    settings: ["openbare apotheek","ziekenhuisapotheek","farmaceutische industrie","VVT (farmaceutische zorg)"],
  },
  {
    slug: "apotheker",
    nameNl: "Apotheker",
    shortNl: "Apotheker",
    aliases: ["openbaar apotheker","ziekenhuisapotheker"],
    category: "wo",
    levelLabel: "WO master (farmacie)",
    bigStatus: "big_artikel_3",
    settings: ["openbare apotheek","ziekenhuis","poliklinische apotheek"],
  },
  {
    slug: "arts",
    nameNl: "Arts",
    shortNl: "Arts",
    aliases: ["basisarts","dokter","ANIOS","AIOS","arts-assistent"],
    category: "wo",
    levelLabel: "WO master (geneeskunde) + artsexamen",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","GGZ","gehandicaptenzorg","huisartsenzorg","ambulancezorg"],
  },
  {
    slug: "arts-maatschappij-en-gezondheid",
    nameNl: "Arts maatschappij en gezondheid",
    shortNl: "Arts M&G",
    aliases: ["arts M en G","sociaal geneeskundige"],
    category: "wo",
    levelLabel: "WO medisch specialisme",
    bigStatus: "big_artikel_3",
    settings: ["GGD","jeugdgezondheidszorg","publieke gezondheid"],
  },
  {
    slug: "wo-geneeskunde-basisarts",
    nameNl: "Geneeskunde (wo-master) - basisarts",
    shortNl: "Basisarts",
    aliases: ["Geneeskunde","basisarts","arts","ANIOS","AIOS","MSc Geneeskunde","Medicine"],
    category: "wo",
    levelLabel: "WO master",
    crebo: "66551",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","GGZ","huisartsenzorg","gehandicaptenzorg","ambulancezorg"],
  },
  {
    slug: "bedrijfsarts",
    nameNl: "Bedrijfsarts",
    shortNl: "Bedrijfsarts",
    aliases: ["arbo-arts"],
    category: "wo",
    levelLabel: "WO medisch specialisme",
    bigStatus: "big_artikel_3",
    settings: ["arbodienst","bedrijfsgezondheidszorg"],
  },
  {
    slug: "gz-psycholoog",
    nameNl: "Gezondheidszorgpsycholoog",
    shortNl: "GZ-psycholoog",
    aliases: ["gz psycholoog","gezondheidszorgpsycholoog","GZ","healthcare psychologist","gz-psycholoog","GZ psycholoog","psycholoog BIG"],
    category: "wo",
    levelLabel: "Postmaster (BIG-opleiding, Wet BIG artikel 3)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","VVT","ziekenhuis","revalidatie","gehandicaptenzorg","jeugdzorg","forensische zorg","vrijgevestigde praktijk"],
  },
  {
    slug: "kaakchirurg",
    nameNl: "MKA-chirurg (kaakchirurg)",
    shortNl: "Kaakchirurg",
    aliases: ["MKA-chirurg","mondziekten kaak- en aangezichtschirurgie"],
    category: "wo",
    levelLabel: "WO specialisme",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","mondzorg"],
  },
  {
    slug: "klinisch-fysicus",
    nameNl: "Klinisch fysicus",
    shortNl: "Klinisch fysicus",
    aliases: ["medisch fysicus","klinisch fysicus audioloog"],
    category: "wo",
    levelLabel: "WO master + postmaster opleiding klinische fysica",
    bigStatus: "big_artikel_34",
    settings: ["ziekenhuis","radiotherapiecentrum","audiologisch centrum"],
  },
  {
    slug: "klinisch-neuropsycholoog",
    nameNl: "Klinisch neuropsycholoog",
    shortNl: "Klinisch neuropsycholoog",
    aliases: ["KNP"],
    category: "wo",
    levelLabel: "WO specialisme",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","revalidatie","GGZ"],
  },
  {
    slug: "klinisch-technoloog",
    nameNl: "Klinisch technoloog",
    shortNl: "Klinisch technoloog",
    aliases: ["klinisch technoloog","Technical Medicine","Technische Geneeskunde","Klinische Technologie","technisch geneeskundige","technische geneeskunde"],
    category: "wo",
    levelLabel: "WO master (Technische Geneeskunde)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","academisch medisch centrum","OK","interventieradiologie","UMC"],
  },
  {
    slug: "wo-psychologie-master",
    nameNl: "Psychologie (wo-master)",
    shortNl: "Master Psychologie",
    aliases: ["Psychologie","MSc Psychologie","master psycholoog","basispsycholoog","Psychology"],
    category: "wo",
    levelLabel: "WO master",
    crebo: "60260",
    bigStatus: "geen_big",
    settings: ["GGZ","ziekenhuis","jeugdzorg","forensische zorg","gehandicaptenzorg"],
  },
  {
    slug: "orthopedagoog-generalist",
    nameNl: "Orthopedagoog-generalist",
    shortNl: "OG",
    aliases: ["OG","orthopedagoog-generalist","orthopedagoog generalist","NVO orthopedagoog-generalist","OG-er"],
    category: "wo",
    levelLabel: "Postmaster (BIG-opleiding, Wet BIG artikel 3)",
    bigStatus: "big_artikel_3",
    settings: ["jeugdzorg","gehandicaptenzorg","onderwijs / samenwerkingsverbanden","GGZ (jeugd)","forensische zorg","GGZ","onderwijs/zorg"],
  },
  {
    slug: "orthodontist",
    nameNl: "Orthodontist",
    shortNl: "Orthodontist",
    aliases: ["dentomaxillaire orthopedie"],
    category: "wo",
    levelLabel: "WO specialisme",
    bigStatus: "big_artikel_3",
    settings: ["mondzorg"],
  },
  {
    slug: "wo-pedagogische-wetenschappen-orthopedagogiek",
    nameNl: "Pedagogische Wetenschappen / Orthopedagogiek (wo-master)",
    shortNl: "Orthopedagoog (wo-master)",
    aliases: ["Orthopedagogiek","Pedagogische Wetenschappen","orthopedagoog","MSc Orthopedagogiek","academisch pedagoog"],
    category: "wo",
    levelLabel: "WO master",
    bigStatus: "geen_big",
    settings: ["jeugdzorg","gehandicaptenzorg","onderwijs","GGZ (jeugd)"],
  },
  {
    slug: "psychotherapeut",
    nameNl: "Psychotherapeut",
    shortNl: "Psychotherapeut",
    aliases: ["psychotherapeut","PT","psychotherapist"],
    category: "wo",
    levelLabel: "Postmaster (BIG-opleiding, Wet BIG artikel 3)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","forensische zorg","vrijgevestigde praktijk","verslavingszorg"],
  },
  {
    slug: "seh-arts",
    nameNl: "SEH-arts KNMG",
    shortNl: "SEH-arts",
    aliases: ["spoedeisende geneeskunde","spoedarts"],
    category: "wo",
    levelLabel: "WO medisch specialisme",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","SEH"],
  },
  {
    slug: "wo-tandheelkunde-tandarts",
    nameNl: "Tandheelkunde (wo) - tandarts",
    shortNl: "Tandarts",
    aliases: ["Tandheelkunde","tandarts","Dentistry","MSc Tandheelkunde"],
    category: "wo",
    levelLabel: "WO master",
    bigStatus: "big_artikel_3",
    settings: ["tandartspraktijk","mondzorgcentrum","ziekenhuis (MKA)","VVT (mondzorg)"],
  },
  {
    slug: "tandarts",
    nameNl: "Tandarts",
    shortNl: "Tandarts",
    aliases: ["dentist"],
    category: "wo",
    levelLabel: "WO master (tandheelkunde)",
    bigStatus: "big_artikel_3",
    settings: ["tandartspraktijk","mondzorg","instellingsmondzorg (VVT/gehandicaptenzorg)"],
  },
  {
    slug: "verzekeringsarts",
    nameNl: "Verzekeringsarts",
    shortNl: "Verzekeringsarts",
    aliases: [],
    category: "wo",
    levelLabel: "WO medisch specialisme",
    bigStatus: "big_artikel_3",
    settings: ["UWV","verzekeringsgeneeskunde"],
  },
  {
    slug: "ambulancechauffeur",
    nameNl: "Ambulancechauffeur",
    shortNl: "Ambulancechauffeur (ACH)",
    aliases: ["ACH","Ambulancechauffeur","Chauffeur ambulancezorg","Ambulanceverpleegkundige chauffeur"],
    category: "specialisatie",
    levelLabel: "Branchediploma (CZO-geaccrediteerd) bovenop MBO niveau 3",
    bigStatus: "geen_big",
    settings: ["regionale ambulancevoorziening (RAV)","ambulancedienst","MICU/interklinisch vervoer"],
  },
  {
    slug: "ambulanceverpleegkundige",
    nameNl: "Ambulanceverpleegkundige",
    shortNl: "Ambulanceverpleegkundige (AVP)",
    aliases: ["AVP","Ambulance verpleegkundige","Verpleegkundige ambulancezorg","Ambulanceverpleegkundige hoogcomplex"],
    category: "specialisatie",
    levelLabel: "CZO-erkende vervolgopleiding bovenop BIG-geregistreerd verpleegkundige",
    bigStatus: "big_artikel_3",
    settings: ["regionale ambulancevoorziening (RAV)","ambulancedienst","MICU","traumahelikopter/HEMS","ambulancezorg","RAV","MMT"],
  },
  {
    slug: "anesthesiemedewerker",
    nameNl: "Anesthesiemedewerker",
    shortNl: "Anesthesiemedewerker",
    aliases: ["AM","Anesthesie-medewerker","Anesthesieassistent","Anesthesiemedewerkster","Anesthesiemedewerker OK","Anesthesie medewerker","anesthesieassistent"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute, hbo duaal)",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (OK/anesthesie)","ZBC","dagbehandeling","pijnbehandelcentrum","ziekenhuis","UMC","zelfstandig behandelcentrum"],
  },
  {
    slug: "arts-verstandelijk-gehandicapten",
    nameNl: "Arts verstandelijk gehandicapten",
    shortNl: "AVG",
    aliases: ["AVG","AVG-arts","arts voor verstandelijk gehandicapten","arts VG"],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14, arts)",
    bigStatus: "big_artikel_3",
    settings: ["gehandicaptenzorg","VVT","poliklinieken AVG","ambulante zorg","AVG-poli"],
  },
  {
    slug: "basis-acute-zorg",
    nameNl: "Basis acute zorg (BAZ)",
    shortNl: "BAZ",
    aliases: ["BAZ","Basis Acute Zorg","Basisopleiding acute zorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (basisbouwsteen acute zorg)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "brandwondenverpleegkundige",
    nameNl: "Brandwondenverpleegkundige",
    shortNl: "Brandwondenverpleegkundige",
    aliases: ["Verpleegkundige brandwondencentrum","Burn care verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["brandwondencentrum","ziekenhuis"],
  },
  {
    slug: "casemanager-dementie",
    nameNl: "Casemanager dementie",
    shortNl: "Casemanager dementie",
    aliases: ["Casemanagement dementie","Dementieverpleegkundige","Casemanager Dementie","Dementieconsulent","Trajectbegeleider dementie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - post-hbo",
    bigStatus: "onbekend",
    settings: ["VVT","thuiszorg","ketenzorg dementie","GGZ"],
  },
  {
    slug: "cardiaccareverpleegkundige",
    nameNl: "Cardiaccareverpleegkundige",
    shortNl: "CCU-verpleegkundige",
    aliases: ["CCU-verpleegkundige","Cardiac care verpleegkundige","Coronary care verpleegkundige","Hartbewaking verpleegkundige","CC-verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "centralist-meldkamer-ambulancezorg",
    nameNl: "Centralist meldkamer ambulancezorg",
    shortNl: "Centralist MKA",
    aliases: ["UCMKA","uitgiftecentralist","C-ZCC","zorgcoordinatiecentrum"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["meldkamer","ambulancezorg"],
  },
  {
    slug: "chauffeur-laag-en-middencomplexe-ambulancezorg",
    nameNl: "Chauffeur Laag- en Middencomplexe Ambulancezorg",
    shortNl: "CHLMC",
    aliases: ["CHLMC","Chauffeur laagcomplexe ambulancezorg","Zorgambulancechauffeur","Chauffeur besteld vervoer"],
    category: "specialisatie",
    levelLabel: "Branchediploma",
    bigStatus: "geen_big",
    settings: ["regionale ambulancevoorziening (RAV)","zorgambulance","gepland/besteld ambulancevervoer"],
  },
  {
    slug: "deskundige-infectiepreventie",
    nameNl: "Deskundige infectiepreventie",
    shortNl: "Deskundige infectiepreventie",
    aliases: ["DI","Adviseur infectiepreventie","Infectiepreventiedeskundige","Hygienist infectiepreventie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute + niet-EPA vervolgopleiding), NLQF 7",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","VVT","GGD","UMC"],
  },
  {
    slug: "diabetesverpleegkundige",
    nameNl: "Diabetesverpleegkundige",
    shortNl: "Diabetesverpleegkundige",
    aliases: ["DVK","Diabetes verpleegkundige","Verpleegkundige diabeteszorg","Diabetesconsulent"],
    category: "specialisatie",
    levelLabel: "Specialisatie - post-hbo",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","huisartsenzorg","poliklinieken","thuiszorg"],
  },
  {
    slug: "dialyse-assistent",
    nameNl: "Dialyse-assistent",
    shortNl: "Dialyse-assistent",
    aliases: ["Dialyseassistent","Assistent dialyse","Dialysemedewerker"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute)",
    bigStatus: "geen_big",
    settings: ["dialysecentrum","ziekenhuis"],
  },
  {
    slug: "dialyseverpleegkundige",
    nameNl: "Dialyseverpleegkundige",
    shortNl: "Dialyseverpleegkundige",
    aliases: ["Dialyse verpleegkundige","Hemodialyse verpleegkundige","Nierdialyse verpleegkundige","Nefrologieverpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","dialysecentrum","thuiszorg"],
  },
  {
    slug: "endoscopieverpleegkundige",
    nameNl: "Endoscopieverpleegkundige",
    shortNl: "Endoscopieverpleegkundige",
    aliases: ["Scopieverpleegkundige","Endoscopie verpleegkundige","MDL-endoscopie verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","ZBC","UMC"],
  },
  {
    slug: "eerst-verantwoordelijk-verzorgende",
    nameNl: "Eerst verantwoordelijk verzorgende",
    shortNl: "EVV'er",
    aliases: ["EVV","Eerstverantwoordelijk verzorgende","Eerst Verantwoordelijke Verzorgende","Contactverzorgende","Zorgcoördinator (VVT)"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (bovenop mbo niveau 3 Verzorgende IG)",
    mboLevel: 3,
    bigStatus: "big_artikel_34",
    settings: ["VVT","verpleeghuis","thuiszorg","gehandicaptenzorg","VVT (verpleeghuis, verzorgingshuis)"],
  },
  {
    slug: "forensisch-verpleegkundige",
    nameNl: "Forensisch verpleegkundige",
    shortNl: "Forensisch verpleegkundige",
    aliases: ["forensische zorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["justitiele inrichting","forensische zorg","politie"],
  },
  {
    slug: "geriatrieverpleegkundige",
    nameNl: "Geriatrieverpleegkundige",
    shortNl: "Geriatrieverpleegkundige",
    aliases: ["Geriatrisch verpleegkundige","Geriatrie- en revalidatiezorgverpleegkundige","Geriatrische en revalidatiezorgverpleegkundige","GRZ-verpleegkundige","Verpleegkundige geriatrie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","geriatrische revalidatiezorg","UMC"],
  },
  {
    slug: "ggz-verpleegkundige",
    nameNl: "GGZ-verpleegkundige",
    shortNl: "GGZ-verpleegkundige",
    aliases: ["Verpleegkundige GGZ","Psychiatrisch verpleegkundige","Verpleegkundige in de GGZ","GGZ verpleegkundige niveau 4","GGZ verpleegkundige niveau 5"],
    category: "specialisatie",
    levelLabel: "Specialisatie - ervaringsgebaseerd (geen aparte diploma-eis)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","forensische zorg","beschermd wonen","crisisdienst","verslavingszorg"],
  },
  {
    slug: "gipsverbandmeester",
    nameNl: "Gipsverbandmeester",
    shortNl: "Gipsverbandmeester",
    aliases: ["GVM","Gipsverbandmeester","Gipsmeester","Gipsverbandmeester SEH"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute), NLQF 6",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis (gipskamer)","SEH","orthopedie/traumatologie poli","ZBC","ziekenhuis","gipskamer"],
  },
  {
    slug: "gespecialiseerd-verzorgende-revalidatiezorg",
    nameNl: "Gespecialiseerd verzorgende revalidatiezorg",
    shortNl: "GRZ-verzorgende",
    aliases: ["GRZ","Gespecialiseerd Verzorgende Revalidatiezorg","Geriatrisch revalidatie verzorgende","Verzorgende geriatrische revalidatiezorg","Remove the bare alias \"GRZ\"","keep only qualified forms (\"GRZ-verzorgende\"","\"Gespecialiseerd verzorgende revalidatiezorg\")"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (bovenop mbo niveau 3 Verzorgende IG)",
    bigStatus: "big_artikel_34",
    settings: ["VVT","geriatrische revalidatiezorg","verpleeghuis"],
  },
  {
    slug: "gespecialiseerd-verzorgende-gerontopsychiatrie",
    nameNl: "Gespecialiseerd verzorgende gerontopsychiatrie",
    shortNl: "GVG'er",
    aliases: ["GVGP","GVG","Gespecialiseerd Verzorgende Gerontopsychiatrie","Verzorgende gerontopsychiatrie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (bovenop mbo niveau 3 Verzorgende IG)",
    bigStatus: "big_artikel_34",
    settings: ["VVT","verpleeghuis","GGZ","gerontopsychiatrie"],
  },
  {
    slug: "gespecialiseerd-verzorgende-psychogeriatrie",
    nameNl: "Gespecialiseerd verzorgende psychogeriatrie",
    shortNl: "GVP'er",
    aliases: ["GVP","Gespecialiseerd Verzorgende Psychogeriatrie","Verzorgende psychogeriatrie","PG-verzorgende","Gespecialiseerd verzorgende psychogeriatrie","Gespecialiseerde Verzorgende Psychogeriatrie","Dementiezorg specialist (verzorgende)"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (bovenop mbo niveau 3 Verzorgende IG)",
    mboLevel: 3,
    bigStatus: "big_artikel_34",
    settings: ["VVT","verpleeghuis","psychogeriatrie","dagbesteding","VVT (psychogeriatrische afdeling, gesloten afdeling)","kleinschalig wonen dementie","thuiszorg (casemanagement dementie, ondersteunend)","dagbesteding ouderen"],
  },
  {
    slug: "gespecialiseerd-verzorgende-somatiek",
    nameNl: "Gespecialiseerd verzorgende somatiek",
    shortNl: "GVS'er",
    aliases: ["GVS","Gespecialiseerd Verzorgende Somatiek","Verzorgende somatiek"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (bovenop mbo niveau 3 Verzorgende IG)",
    bigStatus: "big_artikel_34",
    settings: ["VVT","verpleeghuis","thuiszorg"],
  },
  {
    slug: "hartfalenverpleegkundige",
    nameNl: "Hartfalenverpleegkundige",
    shortNl: "Hartfalenverpleegkundige",
    aliases: ["hartfalen verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","cardiologie","poli"],
  },
  {
    slug: "highcare-kinderverpleegkundige",
    nameNl: "Highcare-kinderverpleegkundige",
    shortNl: "HC-kinderverpleegkundige",
    aliases: ["High care kinderverpleegkundige","HC kinderverpleegkundige","Kinder-HC"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "highcare-neonatologieverpleegkundige",
    nameNl: "Highcare-neonatologieverpleegkundige",
    shortNl: "HC-neonatologieverpleegkundige",
    aliases: ["High care neonatologie verpleegkundige","HC neonatologie","Post-IC/HC neonatologie verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "helpende-plus-niveau-2",
    nameNl: "Helpende plus",
    shortNl: "Helpende Plus",
    aliases: ["Helpende plus","Helpende+","Helpende Zorg en Welzijn plus","Helpende niveau 2 plus","Helpende met verpleegtechnische handelingen"],
    category: "specialisatie",
    levelLabel: "MBO niveau 2 + keuzedeel/mbo-certificaat",
    mboLevel: 2,
    bigStatus: "geen_big",
    settings: ["VVT (verpleeghuis)","thuiszorg","gehandicaptenzorg"],
  },
  {
    slug: "huisarts",
    nameNl: "Huisarts",
    shortNl: "Huisarts",
    aliases: ["huisarts","waarnemend huisarts","HIDHA","general practitioner","GP"],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14, arts)",
    bigStatus: "big_artikel_3",
    settings: ["huisartsenpraktijk","huisartsenpost","eerstelijnszorg","VVT (medische zorg)"],
  },
  {
    slug: "intensive-care-practitioner",
    nameNl: "Intensivecare practitioner",
    shortNl: "IC practitioner",
    aliases: ["ventilation practitioner","circulation practitioner","renal practitioner","neural practitioner"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","IC"],
  },
  {
    slug: "intensivecare-kinderverpleegkundige",
    nameNl: "Intensivecare-kinderverpleegkundige",
    shortNl: "IC-kinderverpleegkundige",
    aliases: ["PICU-verpleegkundige","IC kinderverpleegkundige","Intensive care kinderverpleegkundige","Kinder-IC verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["UMC","ziekenhuis"],
  },
  {
    slug: "intensivecare-neonatologieverpleegkundige",
    nameNl: "Intensivecare-neonatologieverpleegkundige",
    shortNl: "IC-neonatologieverpleegkundige",
    aliases: ["NICU-verpleegkundige","IC neonatologie verpleegkundige","Neonatologie IC verpleegkundige","Neonatologieverpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["UMC","ziekenhuis"],
  },
  {
    slug: "intensivecareverpleegkundige",
    nameNl: "Intensivecareverpleegkundige",
    shortNl: "IC-verpleegkundige",
    aliases: ["IC-verpleegkundige","IC verpleegkundige","Intensive care verpleegkundige","ICU-verpleegkundige","IC-VPK"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "medewerker-interventiecardiologie",
    nameNl: "Medewerker interventiecardiologie",
    shortNl: "Interventiecardiologie",
    aliases: ["hartkatheterisatie","cathlab medewerker"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","cardiologie"],
  },
  {
    slug: "jeugdverpleegkundige",
    nameNl: "Jeugdverpleegkundige",
    shortNl: "Jeugdverpleegkundige",
    aliases: ["JGZ verpleegkundige","jeugdgezondheidszorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["GGD","consultatiebureau","jeugdgezondheidszorg"],
  },
  {
    slug: "kinderoncologieverpleegkundige",
    nameNl: "Kinderoncologieverpleegkundige",
    shortNl: "Kinderoncologieverpleegkundige",
    aliases: ["Kinderoncologie verpleegkundige","Verpleegkundige kinderoncologie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["UMC","ziekenhuis"],
  },
  {
    slug: "kinderverpleegkundige",
    nameNl: "Kinderverpleegkundige",
    shortNl: "Kinderverpleegkundige",
    aliases: ["Kinder verpleegkundige","Pediatrisch verpleegkundige","Verpleegkundige kindergeneeskunde"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC","kinderthuiszorg","gehandicaptenzorg"],
  },
  {
    slug: "kinderverpleegkundige-extramurale-zorg",
    nameNl: "Kinderverpleegkundige extramurale zorg",
    shortNl: "Kinderverpleegkundige extramuraal",
    aliases: ["Kinderthuiszorg verpleegkundige","Kinderverpleegkundige thuiszorg","Extramurale kinderverpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["kinderthuiszorg","thuiszorg","kinderhospice"],
  },
  {
    slug: "klinisch-perfusionist",
    nameNl: "Klinisch perfusionist",
    shortNl: "Klinisch perfusionist",
    aliases: ["perfusionist","hart-longmachine"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","hartchirurgie"],
  },
  {
    slug: "klinisch-psycholoog",
    nameNl: "Klinisch psycholoog",
    shortNl: "Klinisch psycholoog",
    aliases: ["klinisch psycholoog","KP","klinisch neuropsycholoog","specialist gezondheidszorgpsycholoog","klinisch neuropsycholoog (apart specialisme)","[\"KP\""],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14, gezondheidszorgpsycholoog)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","ziekenhuis","forensische zorg","revalidatie","vrijgevestigde praktijk"],
  },
  {
    slug: "kraamverzorgende-niveau-3",
    nameNl: "Kraamverzorgende",
    shortNl: "Kraamverzorgende",
    aliases: ["Kraamverzorgende","Kraamverzorger","Kraamverzorgster","Verzorgende IG kraamzorg","Verzorgende-IG branche Kraamzorg (KZ)","Kraamzorg (KZ)"],
    category: "specialisatie",
    levelLabel: "MBO niveau 3 + keuzedeel kraamzorg (branchevereiste)",
    mboLevel: 3,
    bigStatus: "big_artikel_34",
    settings: ["kraamzorg (thuis)","geboortecentrum","ziekenhuis (kraamafdeling)"],
  },
  {
    slug: "longverpleegkundige",
    nameNl: "Longverpleegkundige",
    shortNl: "Longverpleegkundige",
    aliases: ["COPD-verpleegkundige","Astma/COPD verpleegkundige","Long verpleegkundige","Verpleegkundige longziekten"],
    category: "specialisatie",
    levelLabel: "Specialisatie - post-hbo",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","huisartsenzorg","poliklinieken","thuiszorg"],
  },
  {
    slug: "mammacareverpleegkundige",
    nameNl: "Mammacareverpleegkundige",
    shortNl: "Mammacareverpleegkundige",
    aliases: ["mammacare"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","oncologie"],
  },
  {
    slug: "mammalaborant",
    nameNl: "Mammalaborant",
    shortNl: "Mammalaborant",
    aliases: ["mammografie laborant","screeningslaborant"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","bevolkingsonderzoek"],
  },
  {
    slug: "mediumcareverpleegkundige",
    nameNl: "Mediumcareverpleegkundige",
    shortNl: "MC-verpleegkundige",
    aliases: ["MC-verpleegkundige","Medium care verpleegkundige","MCU-verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "medisch-nucleair-werker",
    nameNl: "Medisch nucleair werker",
    shortNl: "Medisch nucleair werker",
    aliases: ["nucleaire geneeskunde laborant","MNW"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","nucleaire geneeskunde"],
  },
  {
    slug: "medewerker-operatieve-zorg",
    nameNl: "Medewerker Operatieve Zorg",
    shortNl: "MOZ",
    aliases: ["MOZ","Medewerker operatieve zorg","OK-medewerker laag- en middencomplex","Medewerker Operatieve Zorg","OK-medewerker MOZ","Assistent operatieve zorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute)",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (OK)","ZBC","zelfstandig behandelcentrum","huisartsenpraktijk (kleine ingrepen)","ziekenhuis"],
  },
  {
    slug: "neuroverpleegkundige",
    nameNl: "Neuroverpleegkundige",
    shortNl: "Neuroverpleegkundige",
    aliases: ["Neurologie verpleegkundige","Neuro-verpleegkundige","Verpleegkundige neurologie/neurochirurgie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC","revalidatie"],
  },
  {
    slug: "obstetrieverpleegkundige",
    nameNl: "Obstetrieverpleegkundige",
    shortNl: "Obstetrieverpleegkundige",
    aliases: ["O&G-verpleegkundige","Obstetrie- en gynaecologieverpleegkundige","Verloskunde verpleegkundige","Kraamafdeling verpleegkundige","Obstetrie verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC"],
  },
  {
    slug: "oncologieverpleegkundige",
    nameNl: "Oncologieverpleegkundige",
    shortNl: "Oncologieverpleegkundige",
    aliases: ["Oncologisch verpleegkundige","Oncologie verpleegkundige","Verpleegkundige oncologie"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC","thuiszorg","hospice"],
  },
  {
    slug: "operatieassistent",
    nameNl: "Operatieassistent",
    shortNl: "Operatieassistent",
    aliases: ["OA","OK-assistent","Operatie-assistent","Operatieassistente","OK assistent","Operatiekamerassistent","Instrumenterend/omlopend operatieassistent","operatieassistente","instrumenterende"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute, hbo duaal)",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (OK)","ZBC","zelfstandig behandelcentrum","dagbehandeling","ziekenhuis","UMC"],
  },
  {
    slug: "orgaanperfusionist",
    nameNl: "Orgaanperfusionist",
    shortNl: "Orgaanperfusionist",
    aliases: [],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","transplantatie"],
  },
  {
    slug: "verpleegkundige-palliatieve-zorg",
    nameNl: "Verpleegkundige palliatieve zorg",
    shortNl: "Palliatief verpleegkundige",
    aliases: ["Palliatief verpleegkundige","Palliatieve zorg verpleegkundige","Verpleegkundig consulent palliatieve zorg","Post-hbo palliatieve zorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie - post-hbo",
    bigStatus: "big_artikel_3",
    settings: ["hospice","VVT","thuiszorg","ziekenhuis","palliatieve unit"],
  },
  {
    slug: "paro-preventieassistent",
    nameNl: "Paro-preventieassistent",
    shortNl: "Paro-preventieassistent",
    aliases: ["Mondzorgassistent C","Parodontologisch preventieassistent","Paropreventieassistent"],
    category: "specialisatie",
    levelLabel: "Branchecertificaat bovenop MBO niveau 4",
    bigStatus: "geen_big",
    settings: ["tandartspraktijk","parodontologiepraktijk","mondzorgcentrum"],
  },
  {
    slug: "praktijkondersteuner-huisarts",
    nameNl: "Praktijkondersteuner huisarts",
    shortNl: "POH",
    aliases: ["POH","POH-S","POH-GGZ","praktijkondersteuner"],
    category: "specialisatie",
    levelLabel: "Post-hbo/mbo-vervolgopleiding bovenop een basisberoep, geen wettelijke titel",
    bigStatus: "geen_big",
    settings: ["huisartsenpraktijk","gezondheidscentrum"],
  },
  {
    slug: "praktijkondersteuner-huisartsenzorg-ggz",
    nameNl: "Praktijkondersteuner Huisartsenzorg GGZ",
    shortNl: "POH-GGZ",
    aliases: ["POH-GGZ","POH GGZ","Praktijkondersteuner GGZ","Praktijkondersteuner huisarts GGZ"],
    category: "specialisatie",
    levelLabel: "Post-HBO",
    bigStatus: "geen_big",
    settings: ["huisartsenpraktijk","gezondheidscentrum","POH-GGZ pool/detacheerder"],
  },
  {
    slug: "poh-ggz",
    nameNl: "Praktijkondersteuner huisarts GGZ",
    shortNl: "POH-GGZ",
    aliases: ["POH-GGZ","POH GGZ","Praktijkondersteuner GGZ","Praktijkondersteuner huisarts geestelijke gezondheidszorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie - post-hbo leergang (functiegericht)",
    bigStatus: "geen_big",
    settings: ["huisartsenzorg","huisartsenpraktijk","GGZ"],
  },
  {
    slug: "praktijkondersteuner-huisartsenzorg-somatiek",
    nameNl: "Praktijkondersteuner Huisartsenzorg Somatiek",
    shortNl: "POH-S",
    aliases: ["POH-S","POH Somatiek","Praktijkondersteuner somatiek","Praktijkondersteuner huisarts","POH","Praktijkverpleegkundige huisartsenzorg"],
    category: "specialisatie",
    levelLabel: "Post-HBO / NLQF 5-6",
    bigStatus: "geen_big",
    settings: ["huisartsenpraktijk","gezondheidscentrum","zorggroep ketenzorg"],
  },
  {
    slug: "praktijkverpleegkundige-huisartsenzorg",
    nameNl: "Praktijkverpleegkundige huisartsenzorg",
    shortNl: "Praktijkverpleegkundige / POH-S",
    aliases: ["POH-S","POH somatiek","Praktijkondersteuner somatiek","Praktijkondersteuner huisarts","Praktijkverpleegkundige","POH"],
    category: "specialisatie",
    levelLabel: "Specialisatie - post-hbo / functiegerichte scholing",
    bigStatus: "big_artikel_3",
    settings: ["huisartsenzorg","huisartsenpraktijk","gezondheidscentrum"],
  },
  {
    slug: "preventieassistent",
    nameNl: "Preventieassistent",
    shortNl: "Preventieassistent",
    aliases: ["Mondzorgassistent B","Preventie-assistent","PA (mondzorg)"],
    category: "specialisatie",
    levelLabel: "Branchecertificaat bovenop MBO niveau 4",
    bigStatus: "geen_big",
    settings: ["tandartspraktijk","mondzorgcentrum","orthodontiepraktijk"],
  },
  {
    slug: "psychiatrisch-somatisch-verpleegkundige",
    nameNl: "Psychiatrisch somatisch verpleegkundige",
    shortNl: "PSV",
    aliases: ["PSV","Ziekenhuispsychiatrieverpleegkundige","Verpleegkundige ziekenhuispsychiatrie","MPU-verpleegkundige","Medisch psychiatrische unit verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","GGZ","UMC","MPU"],
  },
  {
    slug: "psychiater",
    nameNl: "Psychiater",
    shortNl: "Psychiater",
    aliases: ["psychiater","arts-psychiater","kinder- en jeugdpsychiater","specialist psychiatrie"],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14, arts)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","forensische zorg","ziekenhuis (PAAZ/MPU)","verslavingszorg","crisisdienst","ziekenhuis"],
  },
  {
    slug: "recoveryverpleegkundige",
    nameNl: "Recoveryverpleegkundige",
    shortNl: "Recoveryverpleegkundige",
    aliases: ["Recovery-verpleegkundige","Verkoeverkamer verpleegkundige","PACU-verpleegkundige","Verkoever"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","ZBC","UMC"],
  },
  {
    slug: "sedatiepraktijkspecialist",
    nameNl: "Sedatiepraktijkspecialist",
    shortNl: "Sedatiepraktijkspecialist",
    aliases: ["SPS","Sedatie praktijkspecialist","Sedatiespecialist","PSA-praktijkspecialist","Sedatie praktijk specialist"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-gerichte kernleerroute)",
    bigStatus: "geen_big",
    settings: ["ziekenhuis (endoscopie/radiologie)","ZBC","dagbehandeling","OK/anesthesie","ziekenhuis","UMC","endoscopieafdeling"],
  },
  {
    slug: "spoedeisendehulpverpleegkundige",
    nameNl: "Spoedeisendehulpverpleegkundige",
    shortNl: "SEH-verpleegkundige",
    aliases: ["SEH-verpleegkundige","SEH verpleegkundige","Spoedeisende hulp verpleegkundige","Spoedeisendehulp-verpleegkundige","ER-verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","UMC","huisartsenpost"],
  },
  {
    slug: "specialist-ouderengeneeskunde",
    nameNl: "Specialist ouderengeneeskunde",
    shortNl: "SO",
    aliases: ["SO","specialist ouderengeneeskunde","verpleeghuisarts","ouderengeneeskunde","SOG","verpleeghuisarts (oude naam)","sooc","[\"SO\"","\"verpleeghuisarts\"]"],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14, arts)",
    bigStatus: "big_artikel_3",
    settings: ["VVT","verpleeghuis","geriatrische revalidatiezorg","eerstelijnsverblijf","hospice","geriatrische revalidatie"],
  },
  {
    slug: "sociaal-psychiatrisch-verpleegkundige",
    nameNl: "Sociaal psychiatrisch verpleegkundige",
    shortNl: "SPV",
    aliases: ["SPV","SPV'er","Sociaal-psychiatrisch verpleegkundige","Sociaal Psychiatrisch Verpleegkundige"],
    category: "specialisatie",
    levelLabel: "Specialisatie - postbachelor (NLQF 6)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","crisisdienst","FACT","huisartsenzorg","forensische zorg","verslavingszorg"],
  },
  {
    slug: "stomaverpleegkundige",
    nameNl: "Stomaverpleegkundige",
    shortNl: "Stomaverpleegkundige",
    aliases: ["stomazorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie",
    bigStatus: "geen_big",
    settings: ["ziekenhuis","thuiszorg"],
  },
  {
    slug: "triagist-huisartsenpost",
    nameNl: "Triagist",
    shortNl: "Triagist",
    aliases: ["Triagiste","Triagist huisartsenpost","HAP-triagist","NTS-triagist","Gediplomeerd triagist"],
    category: "specialisatie",
    levelLabel: "Branchediploma bovenop MBO niveau 4 zorg",
    bigStatus: "geen_big",
    settings: ["huisartsenpost","huisartsenpraktijk","meldkamer/zorgcoordinatiecentrum","spoedpost"],
  },
  {
    slug: "verpleegkundig-centralist-meldkamer-ambulancezorg",
    nameNl: "Verpleegkundig centralist meldkamer ambulancezorg",
    shortNl: "Verpleegkundig centralist MKA",
    aliases: ["VCMKA","Verpleegkundig centralist","Meldkamercentralist ambulancezorg","Centralist MKA","Centralist meldkamer ambulancezorg","MKA-centralist"],
    category: "specialisatie",
    levelLabel: "Keep EPA-kernleerroute, but add nlqf_level 5 and drop the note claim that it is \"ingedeeld bij de medisch ondersteunende opleidingen\"",
    bigStatus: "big_artikel_3",
    settings: ["meldkamer ambulancezorg (MKA)","zorgcoordinatiecentrum","regionale ambulancevoorziening (RAV)","ambulancezorg","meldkamer","RAV"],
  },
  {
    slug: "verpleegkundig-endoscopist",
    nameNl: "Verpleegkundig endoscopist",
    shortNl: "Verpleegkundig endoscopist",
    aliases: ["Endoscopist","Scopist","Verpleegkundig scopist"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (niet-EPA vervolgopleiding)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","ZBC","bevolkingsonderzoek darmkanker"],
  },
  {
    slug: "verpleegkundige-middencomplexe-ambulancezorg",
    nameNl: "Verpleegkundige Middencomplexe Ambulancezorg",
    shortNl: "VPMC",
    aliases: ["VPMC","Verpleegkundige middencomplexe ambulancezorg","Zorgambulanceverpleegkundige"],
    category: "specialisatie",
    levelLabel: "CZO-erkende vervolgopleiding bovenop BIG-geregistreerd verpleegkundige",
    bigStatus: "big_artikel_3",
    settings: ["regionale ambulancevoorziening (RAV)","zorgambulance","gepland ambulancevervoer"],
  },
  {
    slug: "verpleegkundig-specialist-agz",
    nameNl: "Verpleegkundig specialist algemene gezondheidszorg",
    shortNl: "VS AGZ",
    aliases: ["VS AGZ","verpleegkundig specialist AGZ","VS algemene gezondheidszorg","nurse practitioner","VS acute zorg","VS chronische zorg","VS intensieve zorg","VS preventieve zorg","Verpleegkundig specialist AGZ","VSAGZ","Nurse practitioner","Verpleegkundig specialist","VS","NP"],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","huisartsenzorg","gehandicaptenzorg","revalidatie","zelfstandig behandelcentrum","UMC","poliklinieken"],
  },
  {
    slug: "verpleegkundig-specialist-ggz",
    nameNl: "Verpleegkundig specialist geestelijke gezondheidszorg",
    shortNl: "VS GGZ",
    aliases: ["VS GGZ","verpleegkundig specialist GGZ","GGZ-VS","VS geestelijke gezondheidszorg","Verpleegkundig specialist GGZ","VSGGZ","Nurse practitioner GGZ","VS ggz","nurse practitioner GGZ"],
    category: "specialisatie",
    levelLabel: "Specialisatie (Wet BIG artikel 14)",
    bigStatus: "big_artikel_3",
    settings: ["GGZ","forensische zorg","verslavingszorg","jeugd-GGZ","POH-GGZ / huisartsenzorg","huisartsenzorg"],
  },
  {
    slug: "wijkverpleegkundige-niveau-5",
    nameNl: "Wijkverpleegkundige (hbo, niveau 5)",
    shortNl: "Wijkverpleegkundige",
    aliases: ["Wijkverpleegkundige niveau 5","HBO-V wijkverpleegkundige","Indicerend wijkverpleegkundige","Wijkverpleegkundige (indicatiesteller)","Verpleegkundige niveau 5 wijk"],
    category: "specialisatie",
    levelLabel: "Specialisatie - hbo-verpleegkundige met deskundigheidsgebied Wijkverpleegkunde",
    bigStatus: "big_artikel_3",
    settings: ["thuiszorg","wijkverpleging","VVT"],
  },
  {
    slug: "wondverpleegkundige",
    nameNl: "Wondverpleegkundige",
    shortNl: "Wondverpleegkundige",
    aliases: ["Wondzorg verpleegkundige","Wondconsulent","Wondexpert","Verpleegkundige wondzorg"],
    category: "specialisatie",
    levelLabel: "Specialisatie - CZO-erkend (EPA-kernleerroute)",
    bigStatus: "big_artikel_3",
    settings: ["ziekenhuis","VVT","thuiszorg","wondexpertisecentrum"],
  },
  {
    slug: "zorgambulancebegeleider",
    nameNl: "Zorgambulancebegeleider",
    shortNl: "Zorgambulancebegeleider",
    aliases: ["Begeleider zorgambulance","Zorgambulance begeleider"],
    category: "specialisatie",
    levelLabel: "Branchediploma bovenop MBO zorgdiploma",
    bigStatus: "geen_big",
    settings: ["regionale ambulancevoorziening (RAV)","zorgambulance","gepland patientenvervoer"],
  },
];
